import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import WhatsAppBtnWrapper from "@/components/layout/whatsapp-btn-wrapper";
import Analytics from "@/components/google/analytics";
import NavbarDesktop from "@/components/layout/navbar-desktop";
import NavbarTouchDynamic from "@/components/layout/navbar-touch/dynamic";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (process.env.NODE_ENV !== "production") {
  // Load Storyblok only in preview mode
  const { initStoryblok } = require("@/lib/storyblok");
  initStoryblok();
}

const jsonLd = {
  logo: {
    "@type": "ImageObject",
    url: "https://www.bunkerdigital.co.uk/path/to/logo.png",
  },
  "@context": "https://schema.org",
  "@type": ["LocalBusiness", "ProfessionalService"],
  "@id": "https://www.bunkerdigital.co.uk/#bunker-digital",
  name: "BunkerDigital",
  alternateName: "Bunker Digital",
  legalName: "BUNKER DIGITAL LIMITED",
  url: "https://www.bunkerdigital.co.uk/",
  email: "info@bunkerdigital.co.uk",
  telephone: "+441613838568",
  address: {
    "@type": "PostalAddress",
    streetAddress: "18 Vaudrey Drive",
    addressLocality: "Hazel Grove",
    addressRegion: "Stockport",
    postalCode: "SK7 5PB",
    addressCountry: "GB",
  },
  contactPoint: [
    {
      "@type": "ContactPoint",
      telephone: "+441613838568",
      contactType: "customer service",
      areaServed: "GB",
      availableLanguage: ["en-GB"],
    },
    {
      "@type": "ContactPoint",
      telephone: "+447935157365",
      contactType: "customer service",
      areaServed: "GB",
      availableLanguage: ["en-GB"],
    },
  ],
  sameAs: [
    "https://www.facebook.com/profile.php?id=61578199581517",
    "https://www.google.com/search?kgmid=/g/11l6ymcs8q&q=BunkerDigital",
    "https://www.bark.com/en/gb/b/bunkerdigital/Xo0AX/",
  ],
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
      ],
      opens: "00:00",
      closes: "23:59",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add JSON-LD to your page */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c"),
          }}
        />
      </head>
      <body className={`${poppins.variable} ${openSans.variable} antialiased`}>
        <Suspense>
          <Analytics />
        </Suspense>
        <WhatsAppBtnWrapper />
        <div className="hidden xl:block">
          <NavbarDesktop />
        </div>
        <div className="xl:hidden">
          <NavbarTouchDynamic />
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
