import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import WhatsAppBtnWrapper from "@/components/layout/whatsapp-btn-wrapper";
import Analytics from "@/components/google/analytics";
import NavbarDesktop from "@/components/layout/navbar-desktop";
import NavbarTouchDynamic from "@/components/layout/navbar-touch/dynamic";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${openSans.variable} antialiased`}>
        <Suspense>
          <Analytics />
        </Suspense>
        <WhatsAppBtnWrapper />
        <div className="hidden xl:block">
          <NavbarDesktop />
        </div>
        <div className="xl:hidden">
          <NavbarTouchDynamic />
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
